wget -P /home/shawn/data/ncep_reanalysis/netcdf/ ftp://ftp.cdc.noaa.gov/Datasets/ncep.reanalysis2/gaussian_grid/prate.sfc.gauss.2000.nc
wget -P /home/shawn/data/ncep_reanalysis/netcdf/ ftp://ftp.cdc.noaa.gov/Datasets/ncep.reanalysis2/gaussian_grid/prate.sfc.gauss.2001.nc
wget -P /home/shawn/data/ncep_reanalysis/netcdf/ ftp://ftp.cdc.noaa.gov/Datasets/ncep.reanalysis2/gaussian_grid/prate.sfc.gauss.2002.nc
wget -P /home/shawn/data/ncep_reanalysis/netcdf/ ftp://ftp.cdc.noaa.gov/Datasets/ncep.reanalysis2/gaussian_grid/prate.sfc.gauss.2003.nc
wget -P /home/shawn/data/ncep_reanalysis/netcdf/ ftp://ftp.cdc.noaa.gov/Datasets/ncep.reanalysis2/gaussian_grid/prate.sfc.gauss.2004.nc
wget -P /home/shawn/data/ncep_reanalysis/netcdf/ ftp://ftp.cdc.noaa.gov/Datasets/ncep.reanalysis2/gaussian_grid/prate.sfc.gauss.2005.nc
wget -P /home/shawn/data/ncep_reanalysis/netcdf/ ftp://ftp.cdc.noaa.gov/Datasets/ncep.reanalysis2/gaussian_grid/prate.sfc.gauss.2006.nc
wget -P /home/shawn/data/ncep_reanalysis/netcdf/ ftp://ftp.cdc.noaa.gov/Datasets/ncep.reanalysis2/gaussian_grid/prate.sfc.gauss.2007.nc
wget -P /home/shawn/data/ncep_reanalysis/netcdf/ ftp://ftp.cdc.noaa.gov/Datasets/ncep.reanalysis2/gaussian_grid/prate.sfc.gauss.2008.nc
wget -P /home/shawn/data/ncep_reanalysis/netcdf/ ftp://ftp.cdc.noaa.gov/Datasets/ncep.reanalysis2/gaussian_grid/prate.sfc.gauss.2009.nc
wget -P /home/shawn/data/ncep_reanalysis/netcdf/ ftp://ftp.cdc.noaa.gov/Datasets/ncep.reanalysis2/gaussian_grid/prate.sfc.gauss.2010.nc
wget -P /home/shawn/data/ncep_reanalysis/netcdf/ ftp://ftp.cdc.noaa.gov/Datasets/ncep.reanalysis2/gaussian_grid/prate.sfc.gauss.2011.nc
wget -P /home/shawn/data/ncep_reanalysis/netcdf/ ftp://ftp.cdc.noaa.gov/Datasets/ncep.reanalysis2/gaussian_grid/prate.sfc.gauss.2012.nc
wget -P /home/shawn/data/ncep_reanalysis/netcdf/ ftp://ftp.cdc.noaa.gov/Datasets/ncep.reanalysis2/gaussian_grid/prate.sfc.gauss.2013.nc
wget -P /home/shawn/data/ncep_reanalysis/netcdf/ ftp://ftp.cdc.noaa.gov/Datasets/ncep.reanalysis2/gaussian_grid/prate.sfc.gauss.2014.nc
wget -P /home/shawn/data/ncep_reanalysis/netcdf/ ftp://ftp.cdc.noaa.gov/Datasets/ncep.reanalysis2/gaussian_grid/prate.sfc.gauss.2015.nc
wget -P /home/shawn/data/ncep_reanalysis/netcdf/ ftp://ftp.cdc.noaa.gov/Datasets/ncep.reanalysis2/gaussian_grid/prate.sfc.gauss.2016.nc
